app.files.ids=input/stock_identifiers.csv
app.files.prices=input/stock_prices.csv
app.files.out=output
app.job.intervals=7,14,30
app.csv.delimiter=,
app.csv.date=yyyy-MM-dd
app.email.subject = ""
app.email.to =""
app.email.body = ""

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
