app.files.ids=C:/Users/ASUS/Downloads/Engine/input/stock_identifiers.csv
app.files.prices=C:/Users/ASUS/Downloads/Engine/input/stock_prices.csv
app.files.out=C:/Users/ASUS/Downloads/Engine/output
app.job.intervals=7,14,30
app.csv.delimiter=,
app.csv.date=yyyy-MM-dd